name: Crypto Auto Poster

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours (change if you want)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          INSTAGRAM_ID: ${{ secrets.INSTAGRAM_ID }}
          CRYPTOPANIC_TOKEN: ${{ secrets.CRYPTOPANIC_TOKEN }}
        run: python bot.py
